image: flauc/firebase

stages:
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - functions/node_modules/

before_script:
  - npm ci
  - npm --prefix functions ci

deploy-prod:
  stage: deploy
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-build/
  script:
    - firebase use genos-glyco --token $FIREBASE_TOKEN
    - npm run target-setup
    - npm run deploy -- -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
